services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    env_file:
      - .env
    volumes:
      - ./n8n_data:/home/node/.n8n
